version: '3.5'

services:
  mysqldb:
    #image: mysql:8.0
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_USER=$MYSQLDB_WODO_USER
      - MYSQL_PASSWORD=$MYSQLDB_WODO_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_WODO_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

volumes: 
  db: